# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_transfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_transfer.proto\"\x1a\n\tFileChunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"#\n\x10\x46ileUploadStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32?\n\x0c\x46ileTransfer\x12/\n\nUploadFile\x12\n.FileChunk\x1a\x11.FileUploadStatus\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_transfer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FILECHUNK']._serialized_start=23
  _globals['_FILECHUNK']._serialized_end=49
  _globals['_FILEUPLOADSTATUS']._serialized_start=51
  _globals['_FILEUPLOADSTATUS']._serialized_end=86
  _globals['_FILETRANSFER']._serialized_start=88
  _globals['_FILETRANSFER']._serialized_end=151
# @@protoc_insertion_point(module_scope)
